# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
    -   id: no-commit-to-branch
-   repo: https://github.com/owasp/lhf.git
    rev: v1.0.1
    hooks:
    -   id: check-sql-injection
        name: Check SQL Injection
        entry: bin/sqlcheck
        language: java
-   repo: https://github.com/gherynos/pre-commit-java
    hooks:
    -   id: pmd
    -   id: cpd
-   repo: https://github.com/jlebar/pre-commit-hooks
    hooks:
    -   id: do-not-submit
